import { Platform, Dimensions } from "react-native";

import colors from "./colors";

export default {
  colors,
  text: {
    fontSize: 18,
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    color: colors.darkGray,
  },
  header: {
    fontSize: 30,
    fontFamily: Platform.OS === "android" ? "Roboto" : "Avenir",
    color: colors.darkGray,
    borderBottomWidth: 1,
    margin: 5,
  },
  button: {
    backgroundColor: "#8888",
    alignItems: "center",
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    height: 54,
    fontSize: 16,
    flexDirection: "column",
    fontWeight: "200",
    fontFamily: "sans-serif",
    padding: 10,
    minWidth: 100,
    margin: 5,
  },
  buttonClicked: {
    backgroundColor: colors.clicked,
  },
  popup: {
    borderWidth: 1,
    borderRadius: 12,
    borderTopWidth: 1,
    borderColor: "rgba(1, 1, 1, .6)",
    backgroundColor: "white",
    zIndex: 1,
    width: "90%",
    height: 450,

    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    overflow: "scroll",

    position: "absolute",
    alignSelf: "center",
    top: Dimensions.get("window").height / 2 - 300,
    elevation: 2,
  },
  treasureView: {
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    width: 200,
    height: 150,
    margin: 10,
    borderColor: "rgba(1, 1, 1, .1)",
    elevation: 2,
  },
  innerTreasureView: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 60,
    width: 60,
    margin: 5,
    padding: 5,
    flexGrow: 1,
    borderColor: "rgba(1, 1, 1, .2)",
    elevation: 1,
  },
  outerScreen: {
    alignContent: "center",
    width: "100%",
    display: "flex",
  },
  innerScreen: {
    display: "flex",
    flexWrap: "wrap",
    alignContent: "center",
    alignItems: "center",
    overflow: "scroll",
    width: "100%",
  },
};
